# Generated by Django 3.2.9 on 2021-12-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211227_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasaprincipala',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
