# Generated by Django 3.2.9 on 2021-12-27 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_clasaprincipala_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AlterModelOptions(
            name='clasaprincipala',
            options={'ordering': ['durata']},
        ),
        migrations.RemoveField(
            model_name='clasaprincipala',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='clasaprincipala',
            name='date',
        ),
        migrations.RemoveField(
            model_name='clasaprincipala',
            name='description',
        ),
        migrations.RemoveField(
            model_name='clasaprincipala',
            name='user',
        ),
        migrations.AddField(
            model_name='clasaprincipala',
            name='durata',
            field=models.TimeField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clasaprincipala',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.workout'),
        ),
    ]
