# Generated by Django 3.2.9 on 2021-12-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_clasaprincipala_counterparticipanti'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasaprincipala',
            options={'ordering': ['oraInceput']},
        ),
        migrations.RenameField(
            model_name='clasaprincipala',
            old_name='durata',
            new_name='oraInceput',
        ),
        migrations.AlterField(
            model_name='clasaprincipala',
            name='listaParticipanti',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True),
        ),
    ]
