# Generated by Django 3.2.9 on 2021-12-27 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20211227_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasaprincipala',
            name='oraInceput',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clasaprincipala',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.workout'),
        ),
    ]
