# Generated by Django 3.2.9 on 2021-12-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20211227_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasaprincipala',
            options={'ordering': ['workout']},
        ),
        migrations.AddField(
            model_name='clasaprincipala',
            name='complete',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
