# Generated by Django 3.2.9 on 2021-12-28 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20211228_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasaprincipala',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
