# Generated by Django 3.2.9 on 2022-01-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_clasaprincipala_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasaprincipala',
            name='counterParticipanti',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='clasaprincipala',
            name='listaParticipanti',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='clasaprincipala',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
